name: remote_rift_desktop
description: "A desktop application that launches and manages the local connector service."
version: 0.1.0
publish_to: "none"

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.5.1
  flutter_bloc: ^9.1.1
  cancelable_stream: ^1.0.0
  draft: ^0.0.12

  remote_rift_connector_api:
    path: ../remote-rift-connector/packages/api
    # git:
    #   url: https://github.com/tomwyr/remote-rift-connector.git
    #   ref: 0.5.1
    #   path: packages/api

  remote_rift_connector_core:
    path: ../remote-rift-connector/packages/core
    # git:
    #   url: https://github.com/tomwyr/remote-rift-connector.git
    #   ref: 0.5.1
    #   path: packages/core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.0
  draft_builder: ^0.0.12

flutter:
  uses-material-design: true
  assets:
    - assets/
